
---
- name: Setup common environment
  hosts: all
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

- name: Setup React environment
  hosts: web
  roles:
    - react

- name: Setup MariaDB environment
  hosts: db
  roles:
    - mariadb
